/**
 * Tokens copiés depuis web/tailwind.config.ts (palette "Burkina Faso" vert/rouge/or) — à garder en
 * synchro manuellement si la palette web change. `fontFamily` diffère volontairement du web : RN n'a
 * pas de `var(--font-*)` CSS, les polices sont chargées via expo-font (voir src/lib/fonts.ts) sous
 * leurs noms littéraux Google Fonts.
 *
 * `boxShadow` (soft-glow/elevated) et `brand-gradient` du web ne se traduisent pas en className RN —
 * voir src/theme/shadows.ts et expo-linear-gradient pour leurs équivalents.
 */
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/app/**/*.{js,jsx,ts,tsx}", "./src/components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "on-background": "#191c1d",
        "surface-dim": "#d9dadb",
        "tertiary-fixed-dim": "#e8c23a",
        error: "#ba1a1a",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-fixed-variant": "#4a3a00",
        "on-surface-variant": "#3e494a",
        "secondary-container": "#EF2B2D",
        surface: "#f8f9fa",
        "on-secondary-fixed-variant": "#7a0d10",
        "surface-container": "#edeeef",
        "surface-variant": "#e1e3e4",
        "on-primary-fixed-variant": "#04502b",
        tertiary: "#a67c00",
        "primary-container": "#009E49",
        "primary-fixed": "#a8e6c1",
        primary: "#046A38",
        "on-secondary-container": "#ffffff",
        "surface-tint": "#00863d",
        "on-primary-container": "#baf2c7",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#f27a7d",
        "outline-variant": "#bec8ca",
        "surface-bright": "#f8f9fa",
        "on-primary-fixed": "#001f0f",
        "surface-container-low": "#f3f4f5",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1d",
        "secondary-fixed": "#ffd0d1",
        "on-secondary-fixed": "#4a0d0f",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#4a3a00",
        "on-error-container": "#93000a",
        "inverse-primary": "#7ed99a",
        "on-tertiary-fixed": "#4a3a00",
        "inverse-surface": "#2e3132",
        "primary-fixed-dim": "#7ed99a",
        outline: "#6f797a",
        background: "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#fcecb0",
        "tertiary-container": "#FCD116",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e7e8e9",
        secondary: "#B71C1C",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "16px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-padding-mobile": "20px",
        "container-padding-desktop": "40px",
      },
      fontFamily: {
        "label-sm": ["Inter_500Medium"],
        "body-md": ["Inter_400Regular"],
        "label-md": ["Inter_600SemiBold"],
        "body-lg": ["Inter_400Regular"],
        "headline-md": ["PlusJakartaSans_600SemiBold"],
        "headline-lg-mobile": ["PlusJakartaSans_700Bold"],
        "headline-lg": ["PlusJakartaSans_700Bold"],
        "display-lg": ["PlusJakartaSans_800ExtraBold"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px" }],
        "body-md": ["16px", { lineHeight: "24px" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em" }],
        "headline-md": ["24px", { lineHeight: "32px" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px" }],
        "body-lg": ["18px", { lineHeight: "28px" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em" }],
      },
    },
  },
  plugins: [],
};
