import type { Config } from "tailwindcss";

/**
 * Palette "Burkina Faso" : vert (primary), rouge (secondary), jaune de l'étoile (tertiary)
 * en accent. Remplace la palette teal/ambre d'origine du design Stitch — mêmes noms de tokens,
 * pour que tous les composants existants héritent du nouveau thème sans modification.
 */
const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#191c1d",
        "surface-dim": "#d9dadb",
        "tertiary-fixed-dim": "#e8c23a",
        error: "#ba1a1a",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-fixed-variant": "#4a3a00",
        "on-surface-variant": "#3e494a",
        "secondary-container": "#EF2B2D",
        surface: "#f8f9fa",
        "on-secondary-fixed-variant": "#7a0d10",
        "surface-container": "#edeeef",
        "surface-variant": "#e1e3e4",
        "on-primary-fixed-variant": "#04502b",
        tertiary: "#a67c00",
        "primary-container": "#009E49",
        "primary-fixed": "#a8e6c1",
        primary: "#046A38",
        "on-secondary-container": "#ffffff",
        "surface-tint": "#00863d",
        "on-primary-container": "#baf2c7",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#f27a7d",
        "outline-variant": "#bec8ca",
        "surface-bright": "#f8f9fa",
        "on-primary-fixed": "#001f0f",
        "surface-container-low": "#f3f4f5",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1d",
        "secondary-fixed": "#ffd0d1",
        "on-secondary-fixed": "#4a0d0f",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#4a3a00",
        "on-error-container": "#93000a",
        "inverse-primary": "#7ed99a",
        "on-tertiary-fixed": "#4a3a00",
        "inverse-surface": "#2e3132",
        "primary-fixed-dim": "#7ed99a",
        outline: "#6f797a",
        background: "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#fcecb0",
        "tertiary-container": "#FCD116",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e7e8e9",
        secondary: "#B71C1C",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "16px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-padding-mobile": "20px",
        "container-padding-desktop": "40px",
      },
      fontFamily: {
        "label-sm": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "label-md": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        "headline-md": ["var(--font-jakarta)"],
        "headline-lg-mobile": ["var(--font-jakarta)"],
        "headline-lg": ["var(--font-jakarta)"],
        "display-lg": ["var(--font-jakarta)"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
      boxShadow: {
        "soft-glow": "0px 4px 20px rgba(0, 158, 73, 0.08)",
        "elevated": "0px 12px 32px rgba(0, 0, 0, 0.1)",
      },
      backgroundImage: {
        "brand-gradient": "linear-gradient(135deg, #EF2B2D 0%, #009E49 100%)",
      },
    },
  },
  plugins: [],
};

export default config;
